name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Install Wintellect-PowerShell
      run: Install-Module -Name WintellectPowerShell -Force -AllowClobber
      if: startsWith(matrix.os, 'windows')
    - name: Install ALSA2 headers
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev
      if: startsWith(matrix.os, 'ubuntu')
    - name: Release build
      run: ./build_portaudio_win.ps1
    - name: Debug build
      run: ./build_portaudio_win.ps1 -DebugBuild
    - name: Upload artifact (debug)
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: portaudio-debug-build-${{ matrix.os }}
        # Directory containing files to upload
        path: portaudio_build/Debug
    - name: Upload artifact (release)
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: portaudio-release-build-${{ matrix.os }}
        # Directory containing files to upload
        path: portaudio_build/Release
